### PR TITLE
fix iOS 13 wrong layout, text and flags overlapped #112 https://githu…

### PR DESCRIPTION
**Pull request by blacktiago**
…b.com/chronotruck/FlagPhoneNumber/issues/112

### CODE REVIEW

**Comment by MEnnabah** [comment]
Any change this can be merged? Maybe to another branch not master?

**Comment by thiagocesarm** [comment]
Thank you for solving the issue! I had to add this piece of code manually because this has not been merged yet, so I hope this PR gets approved soon.

**Comment by thiagocesarm** [comment]
@blacktiago I noticed that when changing the flag's width and height (like `phoneNumberTextField.flagSize = CGSize(width: 48, height: 48)`) it does not update the UI. Could you update the PR's branch to handle this case?

**Comment by thiagocesarm** [comment]
I've tested this solution real quick. Sometimes when the text field is tapped the keyboard does not appear.

**Comment by thiagocesarm** [comment]
There is a problem with this solution. When you input the whole phone number, the left view increases its width. Then, if you end editing the text field and tap it to edit again, the left view captures the touch and the text field does not become the first responder. I was able to notice this using Debug View Hierarchy. 

Still, I am using a modified version of this PR's code while a real solution is not provided.

**Comment by blacktiago** [comment]
@pauloec @thiagocesarm I could try to fix it this weekend but I really need you to add a little xCode project with the issue on it.
Thanks

**Comment by thiagocesarm** [comment]
@grifas Hey, it works, thank you! 

Could you guys add a little more space between the country code and the phone number?
Screen Shot 2019-09-24 at 13 56 08

**Comment by iuliajingoiu** [comment]
checked fix_layout and seems to be working fine. Thanks!

**Pull request closed without merging**
